project_id = "ersqhobqaptsxqclawcc"

[functions.module-chat]
verify_jwt = false

[functions.ingest-source]
verify_jwt = false

[functions.retrieve-spans]
verify_jwt = false

[functions.ai-task-router]
verify_jwt = false

[functions.send-slack-message]
verify_jwt = false

[functions.send-email]
verify_jwt = false